name: aws-v5
on:
  push:
    branches:
      - main

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build:
    runs-on: ubuntu-latest   # 우분투 설치
    steps:
      - name: Checkout
        uses: actions/checkout@v3   # 코드 다운로드 / 적기 귀찮은 것들을 라이브러리(스크립트 모임) 형태로 제공하는 것이 actions 이다.
      - name: Set up JDK 11
        uses: actions/setup-java@v3   # jdk 설치 / 버전마다 다른 jdk 설치 제공
        with:
          java-version: 11
          distribution: zulu
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew   # gradlew 실행권한 부여
      - name: Build with Gradle
        run: ./gradlew clean build   # build 하기
